sqlite_modern_cpp.h

I found a typo for `binder < 10 >`, while declaring `col_10`. It should be `type_10`.
Besides this, is there any way to declare a callback with any number of arguments?
I've been playing with this for a while, and all I could do at the moment is just add more binder struct for each of arguments I need.

FIX typo for binder < 10 >

---

README.md
src/sqlite_modern_cpp.h

Added boost::optional support to deal with NULL values. If a value is unset during an insert,  NULL will be inserted to the database. When querying data, boost::optinal can retain the NULL state from the database.
Added boost::uuids::uuid (stored as blob) to ease work with distributed data
Added std::time_t support(stored as 64 bit integer / utc).
Added method to get the latetest insert ID.

Added some data-types

---

hdr/sqlite_modern_cpp.h

curiously enough, sqlite3.c has 2 instances of this typo

fix "statment" to "statement"

---

README.md
hdr/sqlite_modern_cpp.h
tests/prepared_statment.cc
tests/shared_connection.cc

Major Changes and General Overhaul of the everything.
-Refactored
exceptions into its own namespace
-removed rvalue references where they
are not needed
-made prepared statments possible
-made them
reusable
-removed some template magic

Changed the way arguments are chained #29

---

hdr/sqlite_modern_cpp.h

Since ptr is being passed by value to the lambda expression,
setting ptr to null will have no effect past that single line.
The combination of the code and the comment which implies there
is an additional benefit/security in doing so might mislead a
maintainer or developer down the road.

Removed potentially-misleading dead code and comment

---

hdr/sqlite_modern_cpp/utility/function_traits.h
tests/functors.cc

support functors

---

README.md
hdr/sqlite_modern_cpp.h
tests/nullptr_uniqueptr.cc

@Killili  The most important downside with #51 is that users can only figure out that a value is null or not.
I was thinking that maybe overloading on `nullptr` and `uniqueptr<T>` can solve this problem.
And we can even deprecate boost optional.
Take a look at the new test.

support nullptr and uniqueptr

---

hdr/sqlite_modern_cpp.h
tests/boost_optional.cc
tests/nullptr_uniqueptr.cc
tests/readme_example.cc

Gcc611 fix.

---

hdr/sqlite_modern_cpp.h

Use the already prepared exception classes no_rows and more_rows when
there are no more rows or more rows than expected.

Throw dedicated exceptions

---

hdr/sqlite_modern_cpp.h
tests/std_optional.cc

This is almost like boost::optional, but part of C++17.
So we have the boost::optional interface without a boost dependency.

std::optional support

---

hdr/sqlite_modern_cpp.h

Right now we are arbitrary limited to the standard allocator. Let's fix this.
This is useful in combination with libraries like Botan or Intel TBB, which implement custom allocators.

std::vector allocator support

---

README.md
hdr/sqlite_modern_cpp.h
tests/exceptions.cc

Fixes #80.
Which codes should be used for `no_rows` and `more_rows`?

Expose error codes in exceptions

---

README.md
hdr/sqlite_modern_cpp.h

Fixes #82.
This patch breaks compatibility for non-ASCII database names.

Fix UTF-8 encoding of filenames and SQL statements

---

Makefile.in
hdr/sqlite_modern_cpp.h
hdr/sqlite_modern_cpp/utility/uncaught_exceptions.h
tests/exception_dont_execute.cc
tests/exception_dont_execute_nested.cc
tests/std_optional.cc

std::uncaught_exception will be deprecated with C++17 and might introduce weird bugs at edge cases.

Use std::uncaught_exceptions if possible

---

README.md
hdr/sqlite_modern_cpp.h
tests/exceptions.cc

Add the expanded query string to exceptions.
Additionally this makes the query accessible from the `database_binder`.
Resolves #85

Include SQL statement in exception

---

hdr/sqlite_modern_cpp.h
tests/std_optional.cc

The current build breaks, iff the standard library supports `<optional>`, but C++17 support isn't enabled.
Additionally we should not use _Reserved identifiers.
@aminroosta Should we make a bugfix release(3.0.1?) out of this?

Fix build for modern standard libraries

---

hdr/sqlite_modern_cpp.h

SQLite converts UTF-16 statements anyway, so this should lead to less
code duplication and access to the converted string in case an exception
is thrown.
Fixes #91

Convert UTF-16 statements to UTF-8

---

README.md
hdr/sqlite_modern_cpp.h
tests/flags.cc

Provides the functionality of #72 with the sqlite_config interface.
Fixes #71

Alternative flags and encoding support

---

README.md
hdr/sqlite_modern_cpp.h
hdr/sqlite_modern_cpp/utility/variant.h
tests/variant.cc

The motivating use case for this are custom functions. With `variant`s you can create functions with flexible argument/return types.

std::variant support

---

README.md
hdr/sqlite_modern_cpp.h

Diagnose attempts to execute multistatements

---

hdr/sqlite_modern_cpp/utility/function_traits.h
tests/functions.cc

Mainly useful in combination with SQL functions.

Support function pointers as callbacks

---

hdr/sqlite_modern_cpp.h

I am not sure if I am making the pull request to the right branch or if I have missed something, but the methods of the exception class on the main branch do not allow the exceptions to be caught by const reference as is normally recommended to do.
Modifying the methods to be const fixes the issue.

Fix exceptions so they can be caught by const reference

---

hdr/sqlite_modern_cpp.h
tests/simple_examples.cc

Fixes #104 and lifts the restrictionon on only `int`, `long` and `long long`.

Support all integer types

---

README.md
hdr/sqlite_modern_cpp/log.h
tests/error_log.cc
tests/error_log2.cc

Implement SQL error logging based on error classes.
Closes #109.

Error logging

---

README.md
hdr/sqlite_modern_cpp.h
hdr/sqlite_modern_cpp/errors.h
tests/prepared_statment.cc

Deprecate `reset()` and reset the statement after every execution to avoid bugs.
The patch changes the behaviour of `operator++` to no longer set `used(false)`.
This fixes the loop example in the README.

Auto reset after statement execution

---

hdr/sqlite_modern_cpp.h
tests/simple_examples.cc

Fix #131.
Similar problems may arise with comments after the semicolon, but I don't know how to fix this without effectively writing a parser for SQLite comments.

Allow whitespace after semicolons

---

README.md
hdr/sqlite_modern_cpp.h
tests/std_optional.cc

On macOS, despite the compiler already supporting std::optional, it seems the optional library does not yet exist, meaning we have to rely on std::experimental optional.
I have added that possibility by adding a check for `_MODERN_SQLITE_EXPERIMENTAL_OPTIONAL_SUPPORT`, similar to what is done for the boost::optional. It was implemented in such a way that the experimental::optional is only used if explicitly requested and available.
I also consolidated the implementation of the different optional types. apart from belonging to different namespaces, all optional types work the same, so they were merged together, using the ```using optional = std::optional<T>``` idiom.
The changes should not break existing code which depends on the previous behaviour, but I do not have the normal optional …

Adding std::experimental::optional

---

tests/flags.cc

Fixes the second part of #137.
Thanks to @crapp.

Fix endian detection in flags test for macOS

---

hdr/sqlite_modern_cpp.h
hdr/sqlite_modern_cpp/errors.h
hdr/sqlite_modern_cpp/utility/utf16_utf8.h

Stops using the deprecated <codecvt> header and std::wstring_convert.

Directly use std::codecvt<> without std::wstring_convert<>

---

README.md
hdr/sqlite_modern_cpp.h
hdr/sqlite_modern_cpp/utility/function_traits.h
tests/readme_example.cc

I think this feels more natural than the interface from #103 and it makes lifetime questions easier.
The `database_binder` behaves like a container now:
```c++
for(auto &&row : db << "select age,name,weight from user where age > ? ;" << 21) {
int _age;
string _name;
double _weight;
row >> _age >> _name >> _weight;
cout << _age << ' ' << _name << ' ' << _weight << endl;
}
// or
for(std::tuple<int, string, double> row : db << "select age,name,weight from user where age > ? ;" << 21) {
cout << std::get<int>(row) << ' ' << std::get<string>(row) << ' ' << std::get<double>(row) << endl;
}
```
@Killili What do you think? It's not our usual stream-op interface, but I think this makes it clearer that the range doesn't exists independent from the statement.

Alternative iterator interface

---

hdr/sqlite_modern_cpp.h
hdr/sqlite_modern_cpp/type_wrapper.h

Return extracted values in the type wrapper instead of assigning to references.
This makes the type specific functions easier and avoids unnecessary temporaries in some situations.
Compare https://github.com/SqliteModernCpp/sqlite_modern_cpp/pull/126/files#r163217134

Return values instead of assigning to references

---

hdr/sqlite_modern_cpp/utility/uncaught_exceptions.h
tests/exception_dont_execute_nested.cc

This notably avoids warnings about std::uncaught_exception() being
deprecated from MSVS 2017 (but note that to get it to define __cplusplus
correctly, both /std:c++17 and /Zc:__cplusplus options need to be used,
and these options are only available starting from MSVS 15.7 release).

Define __cpp_lib_uncaught_exceptions if building C++17 mode

---

hdr/sqlite_modern_cpp/errors.h

This avoids having a switch without a case by being more specific withthe default: We expect the default to be hit mostly by errors of the form `SQLITE_ ## NAME`, so we can specify an explicit case for this.
This is no functional change, but it might explain  better what is going on.
AFAICT this would stop Visual C++ from complaining.

Always provide an explicit case in a switch

---

CMakeLists.txt
README.md
hdr/sqlite_modern_cpp.h
hdr/sqlite_modern_cpp/errors.h
hdr/sqlite_modern_cpp/log.h
hdr/sqlite_modern_cpp/type_wrapper.h
hdr/sqlite_modern_cpp/utility/utf16_utf8.h
tests/flags.cc
tests/string_view.cc

The major benefit is if someone tries to bind a `char*` parameter, we can avoid an extra copy that would happen if a new `std::string` was created from it. This pull request also includes some improvements for building/running the tests on MSVC, mostly because I suck at git and didn't know how to separate them into a separate pull request.

Use std::string_view as argument instead of std::string on C++17 Compilers

---

hdr/sqlite_modern_cpp.h
hdr/sqlite_modern_cpp/errors.h
tests/named.cc

This is a UDL based attempt to support binding named parameters: For example
db << "INSERT INTO t VALUES(:firstname, :lastname, :birthday);"
<< ":birthday"_sqlparam("2000-01-01")
<< ":firstname"_sqlparam("John")
<< ":lastname"_sqlparam("Doe");
I am not really happ with the name `_sqlparam`. Does somebody have a better idea?
Another question is how to handle mixed positional and named parameters: Currently `_sqlparam` paameters are ignored in the normal order, so for example
db << "SELECT :abc, ?;" << ":abc"_sqlparam(1) << 2;
would bind both parameters, `1` and `2`, to `:abc` so the result would be `2, NULL`.
This is not perfect but I do not know about a better way and using both named and `?` parameters together is advised against in the SQLite manual anyway, so fixing this might not be …

Support for named and indexed parameters

---

CMakeLists.txt
tests/blob_example.cc
tests/error_log.cc
tests/exception_dont_execute.cc
tests/exception_dont_execute_nested.cc
tests/exceptions.cc
tests/flags.cc
tests/functions.cc
tests/functors.cc
tests/lvalue_functor.cc
tests/mov_ctor.cc
tests/named.cc
tests/nullptr_uniqueptr.cc
tests/prepared_statment.cc
tests/readme_example.cc
tests/shared_connection.cc
tests/simple_examples.cc
tests/std_optional.cc
tests/string_view.cc
tests/trycatchblocks.cc
tests/variant.cc

New hunter make use of `HUNTER_TLS_VERIFY` variable in cmake -- I have switched in `ON`.
For some reason after upgrading the hunter, I couldn't build because `Catch` was not found (hunter would install it but it looks like now it uses `Catch2` package instead of `Catch`...)
I figured out that `CMakeLists.txt` needs updating: `s/Catch/Catch2/`. This works for me on Windows and Linux.

upgrade hunter to newest version (to support MSVC 2019); upgrade to Catch2
